services:
  app:
    build: .
    container_name: qsrac-app
    depends_on:
      - redis
    environment:
      - PYTHONPATH=.
      - CRYPTO_MODE=PQC
      - REDIS_HOST=redis
    volumes:
      - .:/app
      - ./data:/app/data   # 👈 dataset mount
    command: python3 main.py

  redis:
    image: redis:latest
    container_name: qsrac-redis
    ports:
      - "6379:6379"